import argparse
import csv
import math
import os
from typing import Dict, List

import numpy as np
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import mean_absolute_error, mean_squared_error, roc_auc_score


def parse_args():
    parser = argparse.ArgumentParser(description="Compute metrics for case-study predictions.")
    parser.add_argument("--pred-csv", required=True, help="CSV generated by case_study_infer.py")
    parser.add_argument("--task", choices=["regression", "ranking"], required=True)
    parser.add_argument("--topk", type=int, nargs="*", default=[10, 20, 50, 100])
    parser.add_argument("--summary-out", type=str, default=None, help="Optional CSV summary output")
    parser.add_argument(
        "--drop-zero-labels",
        action="store_true",
        help="For regression only. Exclude rows whose experimental_ddg is exactly zero before computing metrics.",
    )
    return parser.parse_args()


def read_rows(path: str) -> List[Dict[str, str]]:
    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_summary(path: str, rows: List[Dict[str, object]]):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else []
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def regression_metrics(rows: List[Dict[str, str]], drop_zero_labels: bool = False) -> Dict[str, float]:
    valid_rows = [r for r in rows if r.get("experimental_ddg", "") != ""]
    if drop_zero_labels:
        valid_rows = [r for r in valid_rows if float(r["experimental_ddg"]) != 0.0]
    y_true = np.array([float(r["experimental_ddg"]) for r in valid_rows], dtype=float)
    y_pred = np.array([float(r["pred_ddg"]) for r in valid_rows], dtype=float)

    pearson = pearsonr(y_true, y_pred)[0] if len(y_true) > 1 else float("nan")
    spearman = spearmanr(y_true, y_pred)[0] if len(y_true) > 1 else float("nan")
    mse = mean_squared_error(y_true, y_pred)
    rmse = math.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)

    binary = (y_true > 0).astype(int)
    auroc = roc_auc_score(binary, y_pred) if len(np.unique(binary)) == 2 else float("nan")

    return {
        "samples": len(valid_rows),
        "drop_zero_labels": drop_zero_labels,
        "pearson": pearson,
        "spearman": spearman,
        "rmse": rmse,
        "mae": mae,
        "auroc": auroc,
    }


def ranking_metrics(rows: List[Dict[str, str]], topk: List[int]) -> Dict[str, object]:
    ranked = sorted(rows, key=lambda x: float(x["pred_ddg"]))
    favorable = [r for r in ranked if int(r.get("is_favorable", "0")) == 1]
    total_favorable = len(favorable)

    result: Dict[str, object] = {"candidates": len(ranked), "favorable": total_favorable}
    if total_favorable == 0:
        return result

    mutation_to_rank = {}
    for idx, row in enumerate(ranked, start=1):
        mutation_to_rank[row["mutation"]] = idx

    for k in topk:
        hit_count = sum(1 for row in ranked[:k] if int(row.get("is_favorable", "0")) == 1)
        result[f"hits_at_{k}"] = hit_count / total_favorable

    rank_percentiles = []
    for row in favorable:
        rank = mutation_to_rank[row["mutation"]]
        rank_percentiles.append(rank / len(ranked))
        print(f"{row['mutation']:>12s}  rank={rank:>4d}  percentile={rank / len(ranked):.4f}  pred_ddg={float(row['pred_ddg']):.6f}")

    result["mean_rank_percentile"] = float(np.mean(rank_percentiles))
    result["median_rank_percentile"] = float(np.median(rank_percentiles))
    return result


def main():
    args = parse_args()
    rows = read_rows(args.pred_csv)

    if args.task == "regression":
        metrics = regression_metrics(rows, drop_zero_labels=args.drop_zero_labels)
        print(f"Samples   : {metrics['samples']}")
        print(f"Drop zero : {metrics['drop_zero_labels']}")
        print(f"Pearson   : {metrics['pearson']:.6f}")
        print(f"Spearman  : {metrics['spearman']:.6f}")
        print(f"RMSE      : {metrics['rmse']:.6f}")
        print(f"MAE       : {metrics['mae']:.6f}")
        print(f"AUROC     : {metrics['auroc']:.6f}")
        if args.summary_out:
            write_summary(args.summary_out, [metrics])
    else:
        metrics = ranking_metrics(rows, args.topk)
        print(f"Candidates : {metrics['candidates']}")
        print(f"Favorable  : {metrics['favorable']}")
        for k in args.topk:
            key = f"hits_at_{k}"
            if key in metrics:
                print(f"Hits@{k:<3}   : {metrics[key]:.6f}")
        if "mean_rank_percentile" in metrics:
            print(f"Mean rank percentile   : {metrics['mean_rank_percentile']:.6f}")
            print(f"Median rank percentile : {metrics['median_rank_percentile']:.6f}")
        if args.summary_out:
            write_summary(args.summary_out, [metrics])


if __name__ == "__main__":
    main()
